config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'welcome#index'
  get '/about', to: 'welcome#show'

  resources :users do
    resources :vehicles
    resources :reviews, except: [:show, :index]
  end

  get '/profile', to: 'users#show'

  resources :trips do
    resources :lift_buddies, only: [:index]
  end

  get '/trip_dashboard', to: "trips/buttons#index"

  get '/trip_dashboard/drivers/new', to: "trips/trips#new", as: :trip_creation
  post '/trip_dashboard/drivers/create', to: "trips/trips#create", as: :trip_create
  get '/trip_dashboard/:id', to: "trips/trips#show", as: :trip_show
  get '/trip_dashboard/edit/:id', to: "trips/trips#edit", as: :trip_edit
  patch '/trip_dashboard/update', to: "trips/trips#update", as: :trip_update
  delete '/trip_dashboard/:id', to: "trips/trips#destroy", as: :trip_destroy

  get "/trip_dashboard/passneger/index", to: "trips/passenger#index", as: :trip_index

  post '/rides/create', to: "trips/rides#create", as: :ride_create
  get '/my_rides', to: "trips/rides#index", as: :my_rides
  delete '/my_rides', to: "trips/rides#destroy", as: :delete_ride


end

app/models/user.rb
class User < ApplicationRecord
  #Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  mount_uploader :picture, PictureUploader
  has_many :vehicles
  has_many :reviews, :dependent => :destroy
  has_many :trips
  has_many :rides
<<<<<<< HEAD

=======
>>>>>>> master
  validates_presence_of :user_name, :first_name, :last_name, :email
  validates_uniqueness_of :user_name

  def avg_rtg
    reviews.average(:rating)
  end

  def has_vehicles?
    vehicles.any?
  end

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
      user.email = auth.info.email
      user.user_name = auth.info.name
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user
      redirect_to trip_dashboard_path, notice: 'Successfully logged in using your Google account.'
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to root_path, alert: 'Something went wrong. Please try to register instead.'
    end
  end
  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_to trip_dashboard_path
        # respond_with resource, location: user_path(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to trip_dashboard_path
    # respond_with resource, location: user_path(resource)
  end

  def destroy
    super
  end

  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.create!(user_params)
    @user.save
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :email, :picture, :pass, :bio, :sport_type)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>


  <div class="field">
    <%= form.label :sport_type %>
    <%= form.text_field :sport_type %>
  </div>

  <div class="field">
    <%= form.label :pass %>
    <%= form.text_field :pass %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>
  
  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= "Editing #{@user.user_name}'s Profile" %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Profile', @user %>

app/views/users/index.html.erb
<h1>Shredders</h1>

<% @users.each do |user| %>
  <dev class="user">
    <img><%= image_tag user.picture_url, width: 200 if user.picture.present? %> </img>
    <ul>
      <li class='user-name'><%= user.user_name %></li>
      <li class='first-name'><%= user.first_name %></li>
      <li class='last-name'><%= user.last_name %></li>
      <li class='pass'><%= user.pass %></li>
      <li class='sport-type'><%= user.sport_type %></li>
      <li class='bio'><%= user.bio %></li>
    </ul>
  </dev>
<br>
<br>

  <%= link_to 'Show', user_path(user) %>
  |
  <%= link_to 'Edit', edit_user_path(user) %>
  |
  <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
  |
  <%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<html>
<body>
<!-- <nav role='navigation'> -->
  <div class="nav-bar">
    <div id='menuToggle'
      <div class="fs-pencil-alt">
        <p class="fas fa-pencil-alt"><%= link_to '  edit', edit_user_path(@user)%></p>
      </div>
    </div>
  <!-- </div> -->

<div class="container">
  <div class='image-circle-show'>
    <% if @user.picture_url == nil %>
    <img> <%= image_tag('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7jFbjBxexVsYsryQaYhSHZ2XSo5Li-pLVAU5nxt2qWqjXkS5d&s', width: 200, height: 200)%>
    <% else %>
    <img> <%= image_tag(@user.picture_url, width: 200, height: 200)%>
    </img>
    <% end  %>
  </div>

    <br>
    <br>

    <h1 class="user-name"><strong><%= @user.user_name %></strong></h1>

  <p>
    <strong>Name:</strong> <br>
    <%= @user.first_name + " " + @user.last_name %>
  </p>

  <p>
    <% if @user.sport_type != nil && @user.sport_type != "" %>
      <strong>Sport Type:</strong> <br>
      <%= @user.sport_type %>
    <% end %>
  </p>

  <p>
    <% if @user.pass != nil && @user.pass != "" %>
      <strong>Ski Pass:</strong> <br>
      <%= @user.pass %>
    <% end %>
  </p>

  <p>
    <% if @user.bio != "" %>
      <strong>Bio:</strong>
      <%= @user.bio %>
    <% end %>
  </p>
  <br>
  <h4>User Reviews:</h4>

  <% if @user.reviews != []%>
  Average User Rating: <%= @user.avg_rtg.round(2) %>/5
    <section class = "reviews">
      <% @user.reviews.each do |review| %>
      <div class='review-card'>
        <u> <%= review.title %></u><br>
         <%= review.content %><br>
        User Rating: <%= review.rating %>/5
      </div>
      <% end %>
      <br>
  <% else %>
    This user doesn't have any reviews yet <br>
  <% end %>
  <%=  link_to 'Edit Review', edit_user_review_path(@user.id) %>
</section> |

<%= link_to 'Edit Profile', edit_user_path(@user.id) %> |
<%= link_to 'Add A Vehicle', new_user_vehicle_path(@user.id) %>|
<%= link_to 'Review Me!', new_user_review_path(@user.id) %>

</body>
</html>