config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'welcome#index'
  get '/about', to: 'welcome#show'

  resources :users do
    resources :vehicles
    resources :reviews, except: [:show, :index]
  end

  get '/profile', to: 'users#show'

  resources :trips do
    resources :lift_buddies, only: [:index]
  end

  get '/trip_dashboard', to: "trips/buttons#index"

  get '/trip_dashboard/drivers/new', to: "trips/trips#new", as: :trip_creation
  post '/trip_dashboard/drivers/create', to: "trips/trips#create", as: :trip_create
  get '/trip_dashboard/:id', to: "trips/trips#show", as: :trip_show
  get '/trip_dashboard/edit/:id', to: "trips/trips#edit", as: :trip_edit
  patch '/trip_dashboard/update', to: "trips/trips#update", as: :trip_update
  delete '/trip_dashboard/:id', to: "trips/trips#destroy", as: :trip_destroy

  get "/trip_dashboard/passneger/index", to: "trips/passenger#index", as: :trip_index

  post '/rides/create', to: "trips/rides#create", as: :ride_create
  get '/my_rides', to: "trips/rides#index", as: :my_rides
  delete '/my_rides', to: "trips/rides#destroy", as: :delete_ride


end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  belongs_to :rtd_location
  has_many :rides, :dependent => :delete_all

  validates_presence_of :seats_available
  validates_presence_of :vehicle_id
  validates_presence_of :rtd_location_id
  validates_presence_of :destination_point
  validates_presence_of :ride_type
end

app/controllers/trips/buttons_controller.rb
class Trips::ButtonsController < ApplicationController

  def index

  end

end

app/controllers/trips/filter_controller.rb
class Trips::FilterController < ApplicationController

  def new

  end

  def create
    
  end

end

app/controllers/trips/lift_buddies_controller.rb
class Trips::LiftBuddiesController < ApplicationController
  def index
    @trip = current_trip
  end

end

app/controllers/trips/passenger_controller.rb
class Trips::PassengerController < ApplicationController

  def index
    @trips = Trip.where("seats_available > 0")
  end

end

app/controllers/trips/rides_controller.rb
class Trips::RidesController < ApplicationController

  def index
    @rides = current_user.rides
  end

  def create
    trip = Trip.find(params[:trip])
    user = current_user
    ride = Ride.create(user_id: user.id, trip_id: trip.id)
    if ride.save
      x = trip.seats_available - 1
      trip.update(seats_available: x)
      redirect_to my_rides_path
    else
      redirect_to trip_index_path
    end
  end

  def destroy
    ride = Ride.find(params[:ride])
    trip = ride.trip
    x = trip.seats_available + 1
    trip.update(seats_available: x)
    ride.destroy
    redirect_to my_rides_path
  end


end

app/controllers/trips/trips_controller.rb
class Trips::TripsController < ApplicationController

  def new
    @current_user = current_user
  end

  # date_of_departure is concatinated here from the day, month and year given
  # only valid dates are accepted to successfully create a trip
  # if a date is invalid, the user is prompted with a message letting them know
  # and they are redirected to the :new page to continue filling out the form.
  def create
    @user = current_user
    @rtd_location = RtdLocation.where(name: params[:rtd_location_id]).first.id
    @vehicle = current_user.vehicles.where(model: params[:vehicle_id].split.last, make: params[:vehicle_id].split.first).first.id
    @date_of_departure = "#{params[:month_of_trip]} #{params[:day_of_trip]} #{params[:year_of_trip]}"
    @trip = Trip.create(user_id: @user.id, vehicle_id: @vehicle, rtd_location_id: @rtd_location, date_of_departure: @date_of_departure, seats_available: params[:seats_available], destination_point: params[:destination_point], ride_type: params[:ride_type])
    if @trip.save
      "Get ready to send! Your trip is created!"
      redirect_to trip_show_path(@trip.id)
    else
      "Sorry jerry! Try it again!"
      @current_user = current_user
      render :new
    end
  end


  def show
    @user = current_user
    @trip = Trip.find(params[:id])
  end

  def edit
    @user = current_user
    @trip = Trip.find(params[:id])
  end

  # A future ice box idea would be to send an email letting passengers
  # know that this trip has been changed and giving them the option to cancel
  # their participation from the email.
  def update
    @user = current_user
    @trip = Trip.find(params[:format])
    rtu = params[:ride_type]
    rtdlu = params[:rtd_location_id]
    sau = params[:seats_available]
    dpu = params[:destination_point]
    if rtu.length > 2
      @trip.update(ride_type: rtu)
    end
    if rtdlu != 0 || nil
      @trip.update(rtd_location_id: rtdlu)
    end
    if sau != nil || " "
      @trip.update(seats_available: sau)
    end
    if dpu.length > 2
      @trip.update(destination_point: dpu)
    end
    if @trip.save
      redirect_to trip_show_path(@trip)
    else
      @trip = @trip
      render :edit
    end
  end

  # A future ice box idea would be to send an email letting passengers
  # know the trip has been canceled and the driver who created the trip
  # could lose reputaiton points on their review score for being flaky.

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to root_path
  end

end

app/views/trips/trips/edit.html.erb
<h1>Change It Up</h1>

<%= form_tag(trip_update_path(@trip), method: "patch") do %>
  <p>Trip Details</p><%= select_tag(:ride_type, options_for_select(trip_list), {class: "trip-field"}) %>

  <p>Strating Station</p><%= select_tag(:rtd_location_id, options_for_select(rtd_location_list), {class: "rtd-field"}) %>
  <p>Seats Available</p><%= select_tag(:seats_available, options_for_select(seats_list), {class: "seat-field"}) %>
  <p>Destination</p><%= select_tag(:destination_point, options_for_select(destination_list), {class: "destination-field"}) %>

  <%= submit_tag('SEND IT', class: "button") %>
<% end %>

app/views/trips/trips/new.html.erb
<section class='trip_creation_form'>
  <h1>Create A New Trip</h1>
  <%= form_tag(trip_create_path, method: "post") do %>
    <p>Trip Details</p><%= select_tag(:ride_type, options_for_select(trip_list), {class: "trip-field"}) %>
    <p>Vehicle</p>
    <% if @current_user.has_vehicles? %>
      <%= select_tag(:vehicle_id, options_for_select(vehicle_list), {class: "vehicle-field"}) %>
    <% else %>
      <%= link_to "Add a vehicle", new_user_vehicle_path(@current_user.id) %>
    <% end %>
    <p>Strating Station</p><%= select_tag(:rtd_location_id, options_for_select(rtd_location_list), {class: "rtd-field"}) %>
    <p>Seats Available</p><%= select_tag(:seats_available, options_for_select(seats_list), {class: "seat-field"}) %>
    <p>Destination</p><%= select_tag(:destination_point, options_for_select(destination_list), {class: "destination-field"}) %>

    <p>Date of Departure</p>
    <p>Day</p><%= select_tag(:day_of_trip, options_for_select(dates_list), {class: "date-field"}) %>
    <p>Month</p><%= select_tag(:month_of_trip, options_for_select(month_list), {class: "month-field"}) %>
    <p>Year</p><%= select_tag(:year_of_trip, options_for_select(year_list), {class: "year-field"}) %>

    <%= submit_tag('SEND IT', class: "button") %>
  <% end %>


</section>

app/views/trips/trips/show.html.erb
<h1>Ready To Shred</h1>
<%= @trip.date_of_departure %>
<%= @trip.ride_type %>
<%= @trip.destination_point %>
<p><%= @trip.vehicle.make %> <%= @trip.vehicle.model %></p>
<%= @trip.rtd_location.name %>

<%= link_to "Flake (Cancel This Trip)", trip_destroy_path(@trip), method: :delete %>
<%= link_to "Change Up (Edit This Trip)", trip_edit_path(@trip) %>