config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'welcome#index'
  get '/about', to: 'welcome#show'

  resources :users do
    resources :vehicles
    resources :reviews, except: [:show, :index]
  end

  get '/profile', to: 'users#show'

  resources :trips do
    resources :lift_buddies, only: [:index]
  end

  get '/trip_dashboard', to: "trips/buttons#index"

  get '/trip_dashboard/drivers/new', to: "trips/trips#new", as: :trip_creation
  post '/trip_dashboard/drivers/create', to: "trips/trips#create", as: :trip_create
  get '/trip_dashboard/:id', to: "trips/trips#show", as: :trip_show
  get '/trip_dashboard/edit/:id', to: "trips/trips#edit", as: :trip_edit
  patch '/trip_dashboard/update', to: "trips/trips#update", as: :trip_update
  delete '/trip_dashboard/:id', to: "trips/trips#destroy", as: :trip_destroy

  get "/trip_dashboard/passneger/index", to: "trips/passenger#index", as: :trip_index

  post '/rides/create', to: "trips/rides#create", as: :ride_create
  get '/my_rides', to: "trips/rides#index", as: :my_rides
  delete '/my_rides', to: "trips/rides#destroy", as: :delete_ride


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shredshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <h5 class='current-user-name'><% if user_signed_in? %>
        Logged in as <strong><%= current_user.user_name %></strong>
        <% end %></h5>
    </div>

    <% if user_signed_in?  %>
      <nav role="navigation">
        <div class="nav-bar">
        <div id="menuToggle">

        <input type="checkbox" />

        <span></span>
        <span></span>
        <span></span>


        <ul id="menu">
          <li><strong><i class="far fa-snowflake"></i>
            <%= link_to "About", "#"%></strong></li>

          <li><strong><i class="fas fa-home"></i>
            <%= link_to "Home", trip_dashboard_path%></strong></li>

            <% if user_signed_in? %>
            <li><strong><i class="fas fa-user"></i>
              <%= link_to "Profile", "/users/#{current_user.id}" %></strong></li>

          <li><strong><i class="fas fa-car-side"></i>
            <%= link_to "My Rides", "#"%></strong></li>

              <% if current_user.vehicles.count >= 1 %>
                <li><strong><i class="fas fa-car"></i>
                <%= link_to "My Vehicles", user_vehicles_path(current_user.id) %></strong></li>
              <% end %>

              <li><strong><i class="fas fa-sign-out-alt"></i>
              <%= link_to "Logout", destroy_user_session_path, method: :delete%></strong></li>

            <% else %>
                <li><strong><i class="fas fa-user-plus"></i>
                  <%= link_to "Sign up", new_user_registration_path %></strong></li>

                <li><strong><i class="fas fa-sign-in-alt"></i>
                  <%= link_to "Login", new_user_session_path %></strong></li>

            <% end %>
        </ul>
        </div>
        </div>
      </nav>
    <% end %>

      <!-- </nav> -->

    <script>
      function openNav() {
        document.getElementById("mySidebar").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
      }

      function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft= "0";
      }
    </script>

    <!-- ----------------------------------------------------------------------- -->

      <div class="container">

        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <%= yield %>
      </div>

      <footer class="navbar-expand-lg">
        <div class="footer">
          <div class="year">
          Shred Share <%= Time.now.year %>
          </div>
        </div>
      </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>